[package]
name = "quic"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
nanorand = "0.7.0"
quinn = "0.9.3"
rcgen = " 0.13.2"
rustls = "0.23.25"
tokio-rustls = "0.26.0"
tokio = {version = "1.28.0", features = ["rt", "rt-multi-thread", "macros", 'io-util']}